---
- name: Setup Terraform and Git
  hosts: all
  become: yes

  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - unzip
        - wget

    - name: Install Terraform
      shell: |
        wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
        unzip terraform_1.0.11_linux_amd64.zip
        mv terraform /usr/local/bin/

    - name: Clone Git Repository
      git:
        repo: 'https://github.com/poorvika0021/ABC-1611.git'
        dest: /home/ExamVM/tf-scripts

    - name: Check for Terraform Configuration Files
      find:
        paths: /home/ExamVM/tf-scripts
        patterns: "*.tf"
      register: tf_files

    - name: Execute Terraform Scripts
      shell: |
        cd /home/ExamVM/tf-scripts
        terraform init
        terraform apply -auto-approve
      register: tf_output
      when: tf_files.matched > 0

    - name: Extract file1_id from Terraform Output
      set_fact:
        file1_id: "{{ tf_output.stdout | regex_search('file1_id = \"(.*)\"', '\\1') }}"
      when: tf_files.matched > 0

    - name: Display Extracted file1_id
      debug:
        msg: "file1_id: {{ file1_id }}"
      when: tf_files.matched > 0
    - name: Cleanup Created and Cloned Files
      file:
        path: /home/{{ ansible_user }}/tf-scripts
        state: absent


